version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-27-alpha
    steps:
      - checkout
      - run: ./gradlew :core:androidDependencies
      - run: ./gradlew :core:lintRelease
      - run: ./gradlew :core:testReleaseUnitTest
      - run: ./gradlew :rx:androidDependencies
      - run: ./gradlew :rx:lintRelease
      - run: ./gradlew :rx:testReleaseUnitTest
      - store_artifacts:
          path: core/build/reports
          destination: reports
      - store_test_results:
          path: core/build/test-results